### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/mongo-changestream-watcher#2]
See: https://github.com/node-casbin/mongo-changestream-watcher/actions/runs/2927758423

![image](https://user-images.githubusercontent.com/3787410/186709550-f22022c8-092a-431c-98d2-a797a9ecc8c5.png)

**Comment by hsluoyz** [comment]
@Sefriol

**Comment by Sefriol** [comment]
MongoDB 6.0 was released just today. I think that's the reason. Dockerfile uses the latest mongodb image. I'll check what are the breaking changes.

EDIT: This has most likely broken the tests for mongoose-adapter as well.

EDIT2: Mongo image does not seem to have mongo command line function, so entry-point.sh scripts fail. https://github.com/docker-library/mongo/issues/558

**Comment by hsluoyz** [comment]
@Sefriol error: https://github.com/node-casbin/mongo-changestream-watcher/runs/8030455397?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/186831980-ad980163-bd73-470c-8e1a-0e21c01cc453.png)

**Comment by Sefriol** [comment]
Hmmph. Tests complete before. I guess the semantic-release does not have access to the cluster anymore..

Should the release script run the tests anyway at this point?

**Comment by hsluoyz** [comment]
@Sefriol refer to other repos: https://github.com/node-casbin

**Comment by Sefriol** [comment]
Other repos do not seem to have husky configured, but it seems that it should be ignored when semantic-release does the release commit.

It seems that I should just disable husky in CI.

EDIT: Yep: https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod
