### ISSUE TITLE
Fix CI error: You cannot publish over the previously published versions: 1.0.0.

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/mongo-changestream-watcher#5]
https://github.com/node-casbin/mongo-changestream-watcher/runs/8038332347?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/186927771-4d338d9c-cd54-44d2-bf61-56c808315328.png)

**Comment by hsluoyz** [comment]
@Sefriol plz refer to: https://github.com/casbin/node-casbin about how to avoid updating version number in package.json manually

**Comment by Sefriol** [comment]
CI is basically a copy from `mongoose-adapter`. I do not think this would affect any future releases, right? I think it was just a bug for the first release where the initial package was added.

I have not modified the `package.json` after `npm init`.

**Comment by hsluoyz** [comment]
@Sefriol can you make a new PR (like a typo fix) to test?

**Comment by Sefriol** [comment]
Pipelines seem to work now as they should @hsluoyz. Closing this.

[![main](https://github.com/node-casbin/mongo-changestream-watcher/actions/workflows/main.yml/badge.svg)](https://github.com/node-casbin/mongo-changestream-watcher/actions/workflows/main.yml)
